database:
  host: "127.0.0.1"
  port: 3306
  name: "your_database"
  user: "root"
  password: ""

web:
  port: 8083
  cert: "path/to/your/cert"
  key: "path/to/your/key"

redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  db: 0 #使用默认数据库